baseurl = "http://nodeschool.io/perth/"
languageCode = "en-us"
title = "Nodeschool Perth"
theme = "hugo-base-theme"

[params]
  description = "Javascript in Isolation"
  mainIcon = "/images/logo-white.svg"

[[params.social]]
    title = "github"
    url = "https://github.com/nodeschool/perth"
    icon = "octocat"